name: BlockPets
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1, wode490390
main: me.petterim1.blockpets.Main
description: BlockPets plugin for Nukkit

permissions:
  blockpets.manage:
    description: "Allows user to manage block-pets"
    default: op
